apiVersion: apps/v1
kind: Deployment
metadata:
  name: raegan-app-iam
  namespace: default
  labels:
    app: raegan-app-iam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raegan-app-iam
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: raegan-app-iam
    spec:
      containers:
        - name: raegan-app-iam
          image: IMAGE_PLACEHOLDER        # <-- sed replaces this with simbudevops7497/raegan-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
